### ISSUE TITLE
Lack of resource validation for nested properties

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#54]
We have received the report that are not validating nested properties in resources e.g.

```  
SomeDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        ...
```

Validator will confirm that `DistributionConfig` is present - it’s a required property, but it will not dive into the properties of `DistributionConfig`.
