### ISSUE TITLE
Validation of Parameters section for AWS-specific parameter types.

### ISSUE THREAD

**Issue by berespt** [Appliscale/perun#63]
Parameters section shouldn't pass validation, when `AllowedValues` field is provided for [AWS-specific parameter types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-specific-parameter-types).

Currently both Perun and AWS assumes that the template is valid.

Template example:

```
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Example which uses allowed values for AWS-specific types
Parameters:
  VpcIdNotWorkingExample:
      Description: >
        If we use AllowedValues here, it will pass the validation, but will cause errors while invoking the template.
        What is more, when creating a stack using AWS console, dropdown with values for this parameter will cease to work.
        The solution is to either remove AllowedValues, or change the parameter type to String.
      Type: AWS::EC2::VPC::Id
      AllowedValues:
        - vpc-deadbeef
        - vpc-d9999999
  VpcIdWorkingExampleWithStringType:
      Description: >
        Using string type solves the problem.
      Type: String
      AllowedValues:
        - vpc-deadbeef
        - vpc-d9999999
  VpcIdWorkingExampleWithNoAllowedValues:
      Description: >
        Removing AllowedValues solves the problem.
      Type: AWS::EC2::VPC::Id

Resources:
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcIdNotWorkingExample
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: foo
        Value: bar
```

Perun should detect this kind of error, especially that AWS documentation is not explicit about the way `AllowedValues` is handled for other types than String.
