### ISSUE TITLE
Basic Styling Guidelines

### ISSUE THREAD

**Issue by afronski** [Appliscale/perun#9]
Goal of our tool is to be a watchdog when it comes to best practices and project related guidelines for _CloudFormation_ templates. At the beginning we would like to have following checks:

- Indentation (e.g. always use _2 spaces_ etc.)
- Suggestions about style:
  - Good practices working with _YAML_ (e.g. formatting, always use / do not use double quotes).
  - Good practices working with _JSON_ (e.g. formatting, line length).
  - Good practices working with _CloudFormation_:
    - Missing `Type` annotations.
    - Highlight missing _Description_ or _Hints_ fields.
    - Not using `>` if lines are too long for _YAML_.
  - Naming conventions for logical names (inside a template).
  - Naming conventions for external names (part of _ARNs_).

Remember about:

- Using multi-level configuration for both:
  - Naming conventions (e.g. project related prefixes).
  - Configuration for enabling / disabling particular options.
- Providing documentation - list of checks, and how to use that command.

**Comment by maxiwoj** [comment]
Wondering what we could check without making any unnecessary yaml/JSON parsing and general styling - I believe that using an external linter would be a better solution here. 

Unfortunately, most of the checks I could think of are either doing the work of a general linter or time-consuming to implement. 

Configuration snippet below that shows possible checks:
```yaml
yaml:
  allowedQuotes: # every type of quotes does another thing, no point in forcing this
    double: true
    single: true
    noquotes: true
  allowedLists: # is there any reason to limit this?
    inline: true
    dash: true

json: # all of those seem more like text editor's checks
  continuationIndent:
    required: true
    value: "        "
  spaces:
    after: [',', ':']
    before: []
  blankLinesAllowed: false



global:
# Editor specific stuff, maybe use external linter for this
  linelength:
    required: true
    value: 100
  indent:
    required: true
    value: "  "

#    AWS Specific
  requiredFields:
    templateDescription: true
    parametersDescription: true

  namingConventions:
    logicalNames: "*" #regex
    externalNames: "*" #regex ---- loads of tedious work in checking the physical name
```
